########################################################
# Start order workflow
# - use case: item available in the inventory

POST http://localhost:8080/order
Content-Type: application/json
Accept: application/json

{ 
    "workflowdata": { 
        "orderId": "{{orderId}}23",
        "item": "1110"
    } 
}

########################################################
# Start order workflow
# - use case: item not available in the inventory

POST http://localhost:8080/order
Content-Type: application/json
Accept: application/json

{ 
    "workflowdata": { 
        "orderId": "{{orderId}}23",
        "item": "1111"
    } 
}


########################################################
# Start order workflow via Cloud Event
# - use case: item available in the inventory
@orderId = 1000

POST http://localhost:8080/
Content-Type: application/json
Accept: application/json
ce-specversion: 1.0
ce-id: {{$guid}}
ce-source: Client
ce-type: OrderEventType
ce-orderid: {{orderId}}

{ 
    "orderId": "{{orderId}}",
    "item": "1110"
}

########################################################
# Shipment via Cloud Event

POST http://localhost:8080/
Content-Type: application/json
Accept: application/json
ce-specversion: 1.0
ce-id: {{$guid}}
ce-source: Shipper
ce-type: ShippingEventType
ce-orderid: {{orderId}}

{ 
    "orderId": "{{orderId}}"
}

########################################################
# Cancel Order via Cloud Event

POST http://localhost:8080/
Content-Type: application/json
Accept: application/json
ce-specversion: 1.0
ce-id: {{$guid}}
ce-source: Client
ce-type: CancelEventType
ce-orderid: {{orderId}}

{ 
    "orderId": "{{orderId}}"
}
